### ISSUE TITLE
Connect to other proxy using credentials 

### ISSUE THREAD

**Issue by Andrewmemo** [gr3p1p3/transparent-proxy#10]
My greetings!

I am trying to use Your package to connect to proxy-server using credentials.

I`ve tried to init server with such option:
```
const server = new ProxyServer({
    verbose: true,
    upstream: function () {
        return 'proxyUserName:proxyPassword@proxyIpAddress:proxyPort';
    },
});
```

I`be checked that the proxy and combination of address&port&username&passwod is valid.

Maybee I am missing a whole idea. Can You help me, please?

Thanks for Your attention :)

**Comment by gr3p1p3** [comment]
Which type of proxy are you using?  Can you give me more details about it? So I can reproduce the bug :)

**Comment by gr3p1p3** [comment]
Closed for unactivity!
