### ISSUE TITLE
async `injectData` against https does not work with multipart

### ISSUE THREAD

**Issue by wwerner** [gr3p1p3/transparent-proxy#21]
It seems making `injectData` work async (#19) isn't as straightforward as I've hoped.
If a `multipart/*` call comes in, the proxy processes the separate chunks and passes them on out of order, as far as I can tell. Resolving this would mean keeping track of processed chunks from a socket before passing them on, I guess. From what I can see it would involve introducing state per connection/message. When playing around with it, I couldn't make it work reliably by awaiting all parts of the call.

[This gist](https://gist.github.com/wwerner/dcaa0e51cc3b1be752ae8dee6cb68c80) contains everything to reproduce.

**Comment by gr3p1p3** [comment]
Does it happen only against https? 
I will have a look at this.

**Comment by wwerner** [comment]
Yes, only for https.

**Comment by gr3p1p3** [comment]
I have to implement some internal counter to upstream request in the right way.
The problem in this case is that the second request will be quickly upstreamed, while the first one is waiting to be solved.

For example, the following code will work:

```javascript
const server = new ProxyServer({
    verbose: true,
    intercept: true,
    injectData: async (data) => {
        let result = data.toString().split('\r\n');
        const separatorIndex = result.findIndex((e) => e === ''); // index to insert header, i.e. as last header
        const header = await getHeader(); //using this every time,
        if (
            result[0] &&
            !result[0].startsWith('--') // don't add header in content chunks
        ) {
            result.splice(separatorIndex, 0, header);
        }
        console.log(result);
        return result.join('\r\n');
    },
});
```

**Comment by gr3p1p3** [comment]
ok! I fixed it! Try with the v1.11.3 and let me know.

**Comment by wwerner** [comment]
Nice! I'll try it on Monday and let you know. Thanks!

**Comment by wwerner** [comment]
Confirming I can't reproduce it w/ `v1.11.7` anymore. I've used the [original reproducer](https://gist.github.com/wwerner/dcaa0e51cc3b1be752ae8dee6cb68c80), used the failing version, then upgraded to 1.11.7 & it worked.

Thanks a ton!

**Comment by gr3p1p3** [comment]
It definitely makes things slower, because the injectData & injectResponse callbacks will pause the socket forcing the upstream to be executed in a "sync" way. 

I close this issue.
