### ISSUE TITLE
Use http-parser-js for parseDataToObject

### ISSUE THREAD

**Issue by leppert** [gr3p1p3/transparent-proxy#23]
Apologies for opening this as an "issue" but it seemed like it might be the easiest place for a conversation. 

I love the conservative use of dependencies in this library but wondered if taking a different tact with [parseDataToObject.js](https://github.com/gr3p1p3/transparent-proxy/blob/91823b290fd3705ce2e49c4fc41013a0f5a5aedf/lib/parseDataToObject.js) might be worthwhile. Specifically, there are nuances around different versions of the http spec (and poor implementations of those specs) that can be challenging to account for and likely out of scope for this project. A few examples that, on a quick read of the current code, might not work as a user expects:

- Cases where a server uses only a single `LF` as a line terminator (discussion [here](https://stackoverflow.com/a/5757349))
- Multi-line headers (discussion [here](https://github.com/curl/curl/issues/8844))
- Multiple-message header fields (discussion [here](https://stackoverflow.com/a/3097052))

All that to say, I wondered if you'd consider using [http-parser-js](https://github.com/creationix/http-parser-js) (or similar) for message parsing instead of the current method. If not, no worries. If so, I might have a go at it if I can find the time.

Thanks again for a useful library.

**Comment by gr3p1p3** [comment]
Thanks for your feedback, I agree with you completely. 
I was wondering if I could use the internal function of nodejs instead to do this.
I will look for a possible solution.

**Comment by leppert** [comment]
Look forward to hearing about what you find! I looked into tapping into the internal Node library but, since the switch to [llhttp](https://github.com/nodejs/llhttp), it seems like it's less obvious how to utilize it from JS. That said, I'd love to see it happen here and crib a bit for another project I'm working on.

**Comment by wwerner** [comment]
Funny, I was down that particular rabbit hole when writing an interceptor, too, also found doing it natively with node cumbersome and reverted to mangling http messages as strings. Didn't like it.

Which is a long-winded way to say: +1 from my side as well, fwiw.

**Comment by leppert** [comment]
I'm digging into this today and hope to have an update later today. 🤞

**Comment by gr3p1p3** [comment]
I'm so sorry about this, but I want to parse the payload self. I built this library several years ago with multiple intentions:

- Understanding how a proxy and HTTP standards work by starting with a simple TCP-Payload
- Quickly configure and enable proxy rotation without, for instance, closing the browser
- Covering Data-Leaks von different Browsers when automating certain tasks in stealth mode.
- Mastering my skills in Node.

It is certainly clear to me that there are still a few steps to go to cover each case, but I think that with the help of all of you and more documentation, we can arrive at an excellent library.

**Comment by leppert** [comment]
No worries at all!
