### ISSUE TITLE
Enable discussions in this repository?

### ISSUE THREAD

**Issue by wwerner** [gr3p1p3/transparent-proxy#24]
Would it be possible to enable the discussion forum in this repo?
I have a few suggestions I'd like to talk about to figure out whether they are interesting for you to decide whether to go forward with my fork or to collaborate.
Most notably, I'd like to switch to Typescript which is rather invasive. Other than that, I'd introduce a proper test framework, linting & editorconfig and automatically generating upstream TLS certificates.

I have slapped together a quick and dirty TS conversion [here](https://github.com/wwerner/transparent-proxy/pull/2/files) but would like to discuss this before proposing a PR.

WDYT?

**Comment by gr3p1p3** [comment]
Honestly, I find no advantages in using typescript and I am not very familiar with it.
We can still talk about it, I have activated the discussions.

https://github.com/gr3p1p3/transparent-proxy/discussions
