### ISSUE TITLE
TLS Support?

### ISSUE THREAD

**Issue by tomelic** [gr3p1p3/transparent-proxy#4]
Awesome initiative and well appreciated,

It would be awesome to see TLS support (or more explanation on how it works given that your readme has an https working example).

Also - could you provide examples of data modifications ?

For example, from messing with the `injectResponse` method I see that the data may be modifyable but it's not decrypted (which is expectable as there is no mention of CA or certificates in the codebase).
```
const ProxyServer = require('transparent-proxy');
const server = new ProxyServer({
    injectResponse: function (maybeData) {
        console.log(maybeData.toString()) // <--- this is encrypted
        return maybeData
  }
});
server.listen(8080, '0.0.0.0', function () {
    console.log('TCP-Proxy-Server started!', server.address());
});

> curl -x 127.0.0.1:8080 https://ifconfig.co
```

this will return:
![image](https://user-images.githubusercontent.com/81975385/113728267-9b855c00-96fe-11eb-9b30-308875509d02.png)

**Comment by gr3p1p3** [comment]
Through the nature of transparent-proxy, data is up/downstreamed as it is (even encrypted).
You could try to implement an sslStrip-Mechanism by capturing/modifyng the session-data before certificates are exchanged.

Honestly, I am still undecided whether to add such a new feature. Any suggestions?

**Comment by tomelic** [comment]
I believe it would cover a lot more user needs that way :)

**Comment by gr3p1p3** [comment]
I add "isHttps"-Attribute to sessionInstance. Download version 1.6.5 and try something like this: 

```javascript
const server = new ProxyServer({
    verbose: true,
    injectResponse: (data,session) => {
        if(!session.isHttps) {
            console.log('SESSION-DATA', data.toString()) //you can spoof here
            return Buffer.from(data.toString().replace('something', 'replaced'));
        }
        return data;
    }
});
```

I will provide this on README.

**Comment by tomelic** [comment]
Awesome!!!

Can you also do an example of injectRequest before it reaches destination? 😅

**Comment by gr3p1p3** [comment]
As the same way ^^
I add some new examples. Here ist a working example of "injectData":

https://github.com/gr3p1p3/transparent-proxy/blob/master/examples/spoofRequest.js

I'm sure it can help to better understand! :)

**Comment by gr3p1p3** [comment]
I add a new feature to intercept encrypted-data.  The "intercept"-Attribute :) It will break secure-connection (obvious), but it allow to intercept & spoof data.

Here a new example: https://github.com/gr3p1p3/transparent-proxy/blob/master/examples/interceptRequest.js

You need to download @1.7.0 for this ^^
