### ISSUE TITLE
Wrong `_response.complete` definition

### ISSUE THREAD

**Issue by fopinappb** [gr3p1p3/transparent-proxy#40]
https://github.com/gr3p1p3/transparent-proxy/blob/cfb761320310d186600e514c022f7678dd107ca1/core/Session.js#L193

On partial response parsing `_response.body` contains the current buffer/body alone, not the entire body until the moment.
Comparing it to `CONTENT_LENGTH` will always fail to mark as completed.

When using `response.body` we see the full body as it is rebuilt from rawResponse buffer instead.
Should some sort of buffer counter be added instead for this check?

I'll gladly open a PR, just wanted to first understand if I'm reading it correctly

**Comment by gr3p1p3** [comment]
You are right! I fixed it on @1.13.2
