### ISSUE TITLE
Allow proxy to verify upstreamHost SSL

### ISSUE THREAD

**Issue by fopinappb** [gr3p1p3/transparent-proxy#41]
https://github.com/gr3p1p3/transparent-proxy/blob/cfb761320310d186600e514c022f7678dd107ca1/core/Session.js#L284C22-L284C22

Could we make this configurable?

**Comment by gr3p1p3** [comment]
Why do you need this? :)

**Comment by fopina** [comment]
Even though we break TLS with the proxy, it means the client trusts the proxy, not the upstream hosts. It would be nice to be able to keep SSL validation in place (at least in some cases) and that needs to be done by the proxy…

**Comment by gr3p1p3** [comment]
Ok, I made a quikly implementation of this. Please download the new version [@1.14.1 ](https://www.npmjs.com/package/transparent-proxy)

You can now initialize your proxy with the `interceptOptions`-Object. Look [here](https://github.com/gr3p1p3/transparent-proxy#options-object)

Or maybe if you need to make this only for certain Sessions, look at `session._interceptOptions` Attribute and modify your options on `upstream`-Callback or on `keys`-Callback.

**Comment by fopina** [comment]
This is awesome, thank you! I'll come back with feedback once I try it out 😃

**Comment by gr3p1p3** [comment]
Let me know :)
