### ISSUE TITLE
Support HTTP range requests

### ISSUE THREAD

**Issue by guifre** [gr3p1p3/transparent-proxy#5]
Seems like the proxy doesn't support partial responses.

If the server returns an HTTP response with accept-ranges: bytes and it's a partial response, it won't process the remaining response, and the client will break.

You can reproduce this by using a selenium browser visiting https://c.disquscdn.com/next/embed/assets/font/icons.4cc7a703d2fdfe684151ff8ac24d45f1.woff2

Thank you

**Comment by gr3p1p3** [comment]
I merged your pull request! It was a bug due to code refactor!! :(

It is on new  @1.78!

Thank you four your help! :)

**Comment by guifre** [comment]
No problem, thanks for building this proxy library, very useful!

**Comment by gr3p1p3** [comment]
You can maybe leave a star, if you like this project 👍
