### ISSUE TITLE
isValidASCII appears to break websocket connections

### ISSUE THREAD

**Issue by GordoRank** [gr3p1p3/transparent-proxy#6]
The new isValidASCII appears to break websocket connections for proxied applications.

If I comment out the `isValid()` check, then the proxied websocket connection works again.

Alternatively, if I modify the `handleProxyTunnel` function to return `onDirectConnectionOpen()` if the `isValid()` check fails, then my proxied application works fine again.

As below:

```
 function handleProxyTunnel(split, data) {
        if (isValid(data.toString())) {
          const firstHeaderRow = split[0];
          const thisTunnel = bridgedConnections[remoteID];

          if (~firstHeaderRow.indexOf(CONNECT)) { //managing HTTP-Tunnel(upstream) & HTTPs
            prepareTunnel(data, firstHeaderRow, true);
          }
          else if (firstHeaderRow.indexOf(CONNECT) === -1
            && !thisTunnel._dst) { // managing http
            prepareTunnel(data, firstHeaderRow);
          }
          else if (thisTunnel && thisTunnel._dst) {
            return onDirectConnectionOpen(data);
          }
          logger.log(remoteID, '=>', thisTunnel.getTunnelStats());
        } else {
          return onDirectConnectionOpen(data);
        }
      }
```

I'm not sure this is the right approach, but I wanted to make you aware.

**Comment by gr3p1p3** [comment]
It was not the right way!! My bad!! I removed this validation!! It was wrong! Can you try again and tell me about it? It should be fixed on @1.7.7
