### ISSUE TITLE
https does not work for me

### ISSUE THREAD

**Issue by jeandybryan** [gr3p1p3/transparent-proxy#8]
server:
```javascript
const ProxyServer = require('transparent-proxy')
const server = new ProxyServer({ verbose: true })
server.listen(10001, '0.0.0.0', function () {
  console.log('TCP-Proxy-Server started!', server.address())
})
```

test:
<img width="642" alt="Screen Shot 2021-06-18 at 1 26 46 PM" src="https://user-images.githubusercontent.com/247002/122597060-d7129f80-d038-11eb-96ea-b027d8a7360c.png">

**Comment by gr3p1p3** [comment]
Ops!! It was my bad! I implemented a bug in last version!! It is fixed on @1.7.7
